language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8"
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - sci_py_import_all
  - python setup.py test
  - sci_py_test_style .
  - python ./misc/sample_project/setup.py test
