version: '3.1'
services:
  jupyter:
    build: ./jupyter/
    ports:
      - "5000:5000"
    volumes:
      - work:/home/jovyan/work
      - /srv/pgsql/tmp:/data:ro
    networks:
      - jupyter
    restart: always  
  
  proxy:
    build: ./proxy_for_proxy/
    volumes:
      - work:/home/jovyan/work:ro
    environment:
      VIRTUAL_HOST: sai.homb.it
      DYNDNS_HOST: sai.homb.it
      LETSENCRYPT_HOST: sai.homb.it
      LETSENCRYPT_EMAIL: sai@homb.it
    networks:
      - jupyter
      - proxy
    depends_on:
      - jupyter
    restart: always  

volumes:
  work:

networks:
  jupyter:
  proxy:
    external:
      name: proxy
